### ISSUE TITLE
Issue in socket.io android

### ISSUE THREAD

**Issue by waqary705** [sreejesh79/android-socket.io-client-demo#1]
Sreejesh sir thank you so much but I have some issue this code working for chat group but I want to chat just specific person then tell me how do I manage dynamically socket channels in android

**Comment by raghavkan149** [comment]
hi sreejesh im unable to run the app prorely and i am new to Nodejs.. and when i try to some msg on it the user getting disconnected giving error message as on cmd window i am getting error as
server listening on port 3000
one user connected /#9axZkY9p6guKj3KqAAAA
one user connected /#E9IarJAG_lc7FbItAAAB
Missing error handler on `socket`.
TypeError: sockets.forEach is not a function
    at Socket.<anonymous> (C:\Users\R\serverdemomaster\index.js:14:17)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (C:\Users\R\serverdemomaster\node_modules\socket.io\lib\socket.js:335:8)
    at Socket.onpacket (C:\Users\R\serverdemomaster\node_modules\socket.io\lib\socket.js:295:12)
    at Client.ondecoded (C:\Users\R\serverdemomaster\node_modules\socket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (C:\Users\R\serverdemomaster\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (C:\Users\R\serverdemomaster\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (C:\Users\R\serverdemomaster\node_modules\socket.io\lib\client.js:175:18)
    at emitOne (events.js:90:13)
one user disconnected /#E9IarJAG_lc7FbItAAAB

**Comment by sreejesh79** [comment]
sockets.forEach is depricated in the new version of socket.io. I have corrected that .. please check
